# yaml-language-server: $schema=https://json.schemastore.org/spring-boot

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rideon
    username: rideon
    password: rideon

application:
  api:
    prefix: /api/v1
  security:
    jwt:
      secret-key: d905357be265e624b63205937219c0d26aab2075b4ba2e663456adaa277edea5
      expiration-ms: 86400000
  cloudinary:
    cloud-name: test
    api-key: test
    api-secret: test