spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rideon
    username: rideon
    password: rideon

application:
  api:
    prefix: /api/v1
  security:
    jwt:
      secret-key: 404D635166546A576E5A7234753778214125442A472D4B6150645367566B5970
      expiration-ms: 86400000