spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 404D635166546A576E5A7234753778214125442A472D4B6150645367566B5970
      expiration-ms: 86400000